=== Klajan/DSA-Alchemie/DSA-Alchemie/resources/data/rezepte.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:simpleType name="laborID">
    <xs:restriction base="xs:byte">
      <xs:minInclusive value="0" />
      <xs:maxInclusive value="2" />
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="laborTXT">
    <xs:restriction base="xs:string">
      <xs:enumeration value="archaisches Labor" />
      <xs:enumeration value="Hexenküche" />
      <xs:enumeration value="Alchimistenlabor" />
      <xs:enumeration value="0" />
      <xs:enumeration value="1" />
      <xs:enumeration value="2" />
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="verfügbarkeit">
    <xs:restriction base="xs:byte">
      <xs:minInclusive value="1" />
      <xs:maxInclusive value="20" />
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="verbreitung">
    <xs:restriction base="xs:byte">
      <xs:minInclusive value="1" />
      <xs:maxInclusive value="7" />
    </xs:restriction>
  </xs:simpleType>
  <xs:element name="rezepte">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" name="rezept">
          <xs:complexType>
            <xs:all minOccurs="1">
              <xs:element minOccurs="0" name="name" type="xs:string" />
              <xs:element minOccurs="1" name="gruppe" type="xs:string" />
              <xs:element minOccurs="1" name="labor" type="laborTXT" />
              <xs:element minOccurs="1" name="probe">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="brauen" type="xs:integer" />
                    <xs:element name="analyse" type="xs:integer" />
                  </xs:sequence>
                </xs:complexType>
              </xs:element>

              <xs:element minOccurs="0" name="beschreibung" />
              <xs:element minOccurs="0" name="beschaffung">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="kosten" type="xs:string" />
                    <xs:element name="seltenheit" type="verfügbarkeit" />
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element minOccurs="0" name="verbreitung" type="xs:string" />
              <xs:element minOccurs="0" name ="merkmale" type="xs:string" />
              <xs:element minOccurs="0" name="haltbarkeit" type="xs:string" />
              <xs:element minOccurs="0" name="preis" type="xs:string" />
              <xs:element minOccurs="0" name="rezeptur" type="xs:string" />
              <xs:element minOccurs="0" name="wirkung">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="M" type="xs:string" />
                    <xs:element name="A" type="xs:string" />
                    <xs:element name="B" type="xs:string" />
                    <xs:element name="C" type="xs:string" />
                    <xs:element name="D" type="xs:string" />
                    <xs:element name="E" type="xs:string" />
                    <xs:element name="F" type="xs:string" />
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element minOccurs="0" name="seite" type="xs:integer" />
              <xs:element minOccurs="0" name="meisterhinweise" type="xs:string" />
            </xs:all>
            <xs:attribute name="name" type="xs:string" use="required" />
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== Klajan/DSA-Alchemie/DSA-Alchemie/resources/data/rezepte.xml
<?xml version="1.0" encoding="utf-8" ?>
<rezepte xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://rezepte.dsa rezepte.xsd">
  <!--
  <rezept name="">
    <gruppe></gruppe>
    <beschaffung>
      <kosten></kosten>
      <seltenheit></seltenheit>
    </beschaffung>
    <rezeptur></rezeptur>
    <beschreibung></beschreibung>
    <labor></labor>
    <probe>
      <brauen></brauen>
      <analyse></analyse>
    </probe>
    <wirkung>
      <M></M>
      <A></A>
      <B></B>
      <C></C>
      <D></D>
      <E></E>
      <F></F>
    </wirkung>
    <verbreitung></verbreitung>
    <merkmale></merkmale>
    <haltbarkeit></haltbarkeit>
    <preis></preis>
    <seite></seite>
    <meisterhinweise></meisterhinweise>
  </rezept>
  -->
  <rezept name="Charismaelixier">
    <name>Charismaelixier</name>
    <gruppe>Virtutica</gruppe>
    <beschaffung>
      <kosten>23 D</kosten>
      <seltenheit>9</seltenheit>
    </beschaffung>
    <rezeptur>
      2 Skrupel Diamantstaub, 5
      Unzen Gratenfelser Schwefelquell,
      7 Unzen geraspeltes Süßholz,
      1 Schössling Finage, 2 Beeren
      Schönaug, 1 Unze Baldrian, 1
      Schlangenzunge
    </rezeptur>
    <beschreibung>
      »Im Tsa-Mond beim Lichte des Aves
      herzustellen. Zerschlag den Diamanten
      und leg die Splitter ins Schwefelwasser,
      welches sich in obsidianenem
      Kelche befindet. Das Süßholz und den
      getruckneten Finage-Schößling zerreib gemeinsam
      und unter Zugabe von etwas Schwefelwasser
      in einem glesernen Mörser. Schönaug und
      Balderian zerdrück in einer Schale aus Alabaster unter
      Beigabe von Schwefelwasser. Stelle nun alle drei Gefeße an die
      Ecken eines Trigramma, welches zum Lichte des Aves offen ist, und
      lasse sie dort sieben Stunden stehen. Lege itzo die Schlangenzunge in
      eine Schale aus Silber in der Mitten des Trigramma und gib die drei
      anderen Theile bei. Rührs um, wobei ein bleuliches Glosen entstehet,
      und lass’s bis zur nechsten Nacht dorten stehen. Itzo destilliers
      in der Retorten ab, wobei die ersten Tropfen, siebenundzwanzig an
      der Zahl, das gewünschte Elixir sind, welches drei Monde lang seine
      Wirkung erhelt, dich schön in Aussehen, Mimik und Sprache zu
      machen wie den großen Levthan vor seinem Sturz.«
      —Pheredonios Melenaar, Die Macht der Elemente,
      Zorgan, ca. 700 BF
    </beschreibung>
    <labor>Hexenküche</labor>
    <probe>
      <brauen>5</brauen>
      <analyse>4</analyse>
    </probe>
    <wirkung>
      <M>
        1, 4, 14, 18, 23, 36, 39, 40; man hat auch schon von gespaltenen
        Zungen und glasigen Schlangenaugen gehört.
      </M>
      <A>
        1 CH-Punkt für 1 SR mit leicht triebhaftem Verhalten
        (KL–1 für 1 Stunde)
      </A>
      <B>
        2 CH-Punkte für 2 SR
      </B>
      <C>
        3 CH-Punkte für 3 SR
      </C>
      <D>
        7 CH-Punkte für 7 SR
      </D>
      <E>
        Das CH des Anwenders steigt für einen Tag um 2 Punkte.
      </E>
      <F>
        Der Anwender aalt sich einen Tag lang in seiner Schönheit
        und Überzeugungskraft (CH +5), ist jedoch ansonsten
        für nichts zu gebrauchen (alle anderen geistigen Eigenschaften
        –2).
      </F>
    </wirkung>
    <verbreitung>5</verbreitung>
    <merkmale>klare, hellblaue Flüssigkeit, riecht nach Baldrian</merkmale>
    <haltbarkeit>W6+9 Wochen</haltbarkeit>
    <preis>etwa 45 Dukaten</preis>
    <seite>39</seite>
    <meisterhinweise>
      Ab einer Qualität von D wird für die Wirkungsdauer
      der Nachteil Widerwärtiges Aussehen zu Unansehnlich,
      dieser zu einem normalen Aussehen abgemildert;
      normales Aussehen wird zum Vorteil Gutaussehend
      und jener steigert sich zu einem Herausragenden
      Aussehen (jedoch ist nur eine
      Steigerung möglich). Bei Qualität M
      ist die Wirkung nicht nur umgekehrt,
      sondern bringt gar zwei Absenkungen
      mit sich. Auf Katzen hat der
      Anwender übrigens eine überaus
      anziehende Wirkung.
    </meisterhinweise>
  </rezept>
  <rezept name="Fingerfertigkeitselixier">
    <gruppe>Virtutica</gruppe>
    <beschaffung>
      <kosten>15 D</kosten>
      <seltenheit>8</seltenheit>
    </beschaffung>
    <rezeptur>
      5 Unzen reiner Alkohol, 1
      Skrupel grob zerhauener Topas, 1 Büschel
      Haare vom Mengbiller Affen, 5 Unzen
      Zwiedestillat, eine rechte Vorderpfote vom Feh,
      1 Bund Atmon, 1 Schössling Finage
    </rezeptur>
    <beschreibung>
      »Im Firunmond beim Lichte der Simia herzustellen. Gieß den
      Alcohol vorsichtig über die Splitter des Topaz, laß es stehen für
      drei Stunden, gib hinzu die Haare vom Aff, welche du selbige drei
      Stunden gekocht im Zwiedestillat. Rühr um. Dreimal nach links.
      Mit der Pfote vom Feh. So ists wohlgetan. Laß nun wieder stehn
      eine Stund ohne jegliches Licht. Derweil zermahl in messingnem
      Mörser Atmon und Finage zu einem Brei und kratz alles aus, was
      du nur findest. Hinein in die Retort. Gib nun die gallig Brüh noch
      kochend hinzu und dann VIEL Hitze im Ofen. Warte nun, bis
      die Farbe wird von rot auf gelb, und nimm sodann die Hitze weg.
      Warte nochmals eine Stund. Es bleibet auf dem Grunde wohl eine
      halbe Unze bernsteinfarbener Flüssigkeit, welche ist ein Elixier,
      das der Fingerfertigkeit höchst förderlich. Dunkel gestellet oder in
      geschlossenem Gefeß aufbewahrt, helt es sich wohl 3 Viertel Jahr.«
      —Pheredonios Melenaar, Die Macht der Elemente,
      Zorgan, ca. 700 BF
    </beschreibung>
    <labor>archaisches Labor</labor>
    <probe>
      <brauen>6</brauen>
      <analyse>5</analyse>
    </probe>
    <wirkung>
      <M>1, 2, 3, 4, 8, 9, 18, 23, 27, 29</M>
      <A>
        1 FF-Punkt für 1 SR, aber erhöhte Schreckhaftigkeit (MU–1
        für 1 Stunde)
      </A>
      <B>
        1 FF-Punkt für 1 SR, aber erhöhte Schreckhaftigkeit (MU–1
        für 1 Stunde)
      </B>
      <C>
        1 FF-Punkt für 1 SR, aber erhöhte Schreckhaftigkeit (MU–1
        für 1 Stunde)
      </C>
      <D>
        7 FF-Punkte für 7 SR
      </D>
      <E>
        Ein wahres Wundermittel: Schlösser wären überhaupt kein
        Problem mehr (FF +15 für 1 SR), wenn nur die Dietriche
        nicht so fürchterlich schwer wären (KK –7 für 3 SR).
      </E>
      <F>
        Auch bekannt als Kleptomanicum: Die erhöhte FF (+7 für
        7 Stunden) will doch ach so gerne demonstriert werden – an
        fremder Leute Börsen, den Miederschnüren erhabener Damen
        (für den Wirkungszeitraum Nachteil Kleptomanie 7).
      </F>
    </wirkung>
    <verbreitung>4</verbreitung>
    <merkmale>bernsteinfarbene, undurchsichtige Flüssigkeit, geruchlos</merkmale>
    <haltbarkeit>W3+7 Monate</haltbarkeit>
    <preis>um 30 Dukaten</preis>
    <seite>39</seite>
    <meisterhinweise>
      Nimmt ein Anwender binnen zweier Tage
      nach einem Genuss von Fingerfertigkeitselixier auf Atmon-
      Basis ein solches ein zweites Mal ein, so bleibt der Trank bis
      auf FF –1 für eine Stunde wirkungslos. Bestimmte alternative
      Rezepturen versuchen die starken Nebenwirkungen bei Qualität
      E zu umgehen (was allgemein natürlich bei allen Alchimika
      gilt).
    </meisterhinweise>
  </rezept>
  <rezept name="Gewandtheitselixier">
    <gruppe>Virtutica</gruppe>
    <beschaffung>
      <kosten>25 D</kosten>
      <seltenheit>6</seltenheit>
    </beschaffung>
    <rezeptur>
      2 Skrupel Smaragdstaub, 10 Unzen Zwiedestillat,
      3 Kolben Mibelrohr, 1 Schössling Finage, 7 Haare eines Einhornschweifs,
      12 lebende Fliegen, 1/2 Unze Gelbes Feuerkraut,
      1 Unze reiner Alkohol
    </rezeptur>
    <beschreibung>
      »Im Phex-Mond beim Lichte des Simia herzustellen. Zerhau den
      Emerald zu grünlichem Staube, welchen du dem Zwiedestillathe
      beifügest, das sich in silberner Kanne befindet. Derweil es dorten
      sprudelt und zischt, zerdrück das Mibelrohr und den Schößling des
      Finage in einer güldnen Schale, bis dass kein Safft mehr herausquillt,
      gib selbigen zum Destillathe. Fülle nun eine Retort mit den
      Haaren und den thunlichst quicklebendig Fliegen. Das trucken
      Feuerkraut zerreib und thues bei. Stell itzo den Feuerofen mit der
      Retort inmitten eines Octagramma, offen gen Simia. Gib nun das
      Destillath in die Retort (und acht darauf, dass die Fliegen drinne
      bleiben) und machs heiß, bis es rötlich brodelt. Dann laß wieder
      kalt werden. Wenn du das Gebreu itzo wieder erhitzt, dann sei die
      Farbe von klarem Gelb. Nun destilliers weiter, bis dass du siebenunddreißig
      Tropfen gefangen hast, welche du in Alcohole verdünnest
      und so das Elixir der Hohen Geschicklichkeit erhelst. Es mag
      dir wohl ein Jahr lang von Nutzen sein.«
      —Pheredonios Melenaar, Die Macht der Elemente,
      Zorgan, ca. 700 BF
    </beschreibung>
    <labor>Hexenküche</labor>
    <probe>
      <brauen>6</brauen>
      <analyse>7</analyse>
    </probe>
    <wirkung>
      <M>
        1, 2, 3, 4, 8, 9, 15, 18, 23, 27, 30, 38
      </M>
      <A>
        1, 2, 3, 4, 8, 9, 15, 18, 23, 27, 30, 38
      </A>
      <B>
        2 GE-Punkte für 2 SR
      </B>
      <C>
        3 GE-Punkte für 3 SR
      </C>
      <D>
        7 GE-Punkte für 7 SR
      </D>
      <E>
        Ein potentes Gebräu, das die GE für zwölf Stunden um 3
        Punkte steigert.
      </E>
      <F>
        Wer bereit ist, für einen halben Tag nach Ablauf der Wirkung
        mit zitternden Gliedern daniederzuliegen (GE –7, FF
        und KK je –2), nur um sich kurzfristig der Gewandtheit einer
        Katze zu erfreuen (GE +12 für 3 SR), der mag dieses Mittel
        wohl schätzen.
      </F>
    </wirkung>
    <verbreitung>5</verbreitung>
    <merkmale>
      klare, gelbe Flüssigkeit, stark alkoholisch
    </merkmale>
    <haltbarkeit>W3+10 Monate</haltbarkeit>
    <preis>um 50 Dukaten</preis>
