=== Klajan/DSA-Alchemie/DSA-Alchemie/data/data.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:simpleType name="labID">
    <xs:restriction base="xs:byte">
      <xs:minInclusive value="0" />
      <xs:maxInclusive value="2" />
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="rareInt">
    <xs:restriction base="xs:byte">
      <xs:minInclusive value="1" />
      <xs:maxInclusive value="20" />
    </xs:restriction>
  </xs:simpleType>
  <xs:element name="Alchemie">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" name="rezept">
          <xs:complexType>
            <xs:sequence>
              <xs:element minOccurs="1" name="name" type="xs:string" />
              <xs:element minOccurs="1" name="gruppe" type="xs:string" />
              <xs:element minOccurs="0" name="beschaffung">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="kosten" type="xs:string" />
                    <xs:element name="seltenheit" type="rareInt" />
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              
              <xs:element minOccurs="1" name="labor" type="labID" />
              <xs:element minOccurs="1" name="probe">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="brauen" type="xs:integer" />
                    <xs:element name="analyse" type="xs:integer" />
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element minOccurs="0" name="verbreitung" type="xs:integer" />
              <xs:element minOccurs="0" name ="merkmale" type="xs:string" />
              <xs:element minOccurs="0" name="haltbarkeit" type="xs:string" />
              <xs:element minOccurs="0" name="preis" type="xs:string" />
              <xs:element minOccurs="0" name="rezeptur" type="xs:string" />
              <xs:element minOccurs="0" name="wirkung">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="M" type="xs:string" />
                    <xs:element name="A" type="xs:string" />
                    <xs:element name="B" type="xs:string" />
                    <xs:element name="C" type="xs:string" />
                    <xs:element name="D" type="xs:string" />
                    <xs:element name="E" type="xs:string" />
                    <xs:element name="F" type="xs:string" />
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element minOccurs="0" name="seite" type="xs:integer" />
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== Klajan/DSA-Alchemie/DSA-Alchemie/data/data.xml
<?xml version="1.0" encoding="utf-8" ?>
<Alchemie xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.w3.org/2001/XMLSchema data.xsd">
  <rezept>
    <name>Heiltrank</name>
    <gruppe>Spagyrik</gruppe>
    <beschaffung>
      <kosten>5 D</kosten>
      <seltenheit>14</seltenheit>
    </beschaffung>
    <labor>0</labor>
    <probe>
      <brauen>2</brauen>
      <analyse>1</analyse>
    </probe>
    <verbreitung>7</verbreitung>
    <merkmale>klare Flüssigkeit mit erfrischendem Geruch</merkmale>
    <haltbarkeit>1W6+20 Monate</haltbarkeit>
    <preis>ab 10 Dukaten; bis zu 2 / LeP</preis>
    <rezeptur>
      der Schwanz einer beliebigen Eidechse, 1 Skrupel
      Gold, 1 Arganwurzel oder 1 Bund Wirselkraut, 10 Unzen
      Morgentau
    </rezeptur>
    <wirkung>
      <M>
        1, 3, 5, 18, 19, 21, 22, 24, Gebräu erzeugt 2W6 SP bei heftigem
        Erbrechen
      </M>
      <A>
        Der Anwender regeneriert augenblicklich 1W6 LeP, erleidet
        jedoch eine leichte Sinnestrübung (KL, GE –1 für 1 Stunde).
      </A>
      <B>augenblickliche Regeneration von 1W6+2 LeP</B>
      <C>2W6+4 LP</C>
      <D>3W6+6 LP</D>
      <E>Alle LP</E>
      <F>
        Der Trank bringt 3W6+25 LeP zurück, auch über das Maximum
        hinaus, neutralisiert jedoch die Wirkung aller anderen
        alchimistisch-magischen Tränke, Gifte und Elixiere für eine
        Woche (also auch alle weiteren Heiltränke, die innerhalb der
        nächsten Woche genossen werden).
      </F>
    </wirkung>
    <seite>56</seite>
  </rezept>
  <rezept>
    <name>Beschwörungskerzen</name>
    <gruppe>Magika</gruppe>
    <beschaffung>
      <kosten>25 S</kosten>
      <seltenheit>10</seltenheit>
    </beschaffung>
    <labor>0</labor>
    <probe>
      <brauen>3</brauen>
      <analyse>0</analyse>
    </probe>
    <verbreitung>6</verbreitung>
    <merkmale>grünliches Wachs, latenter Geruch der Niederhöllen</merkmale>
    <haltbarkeit>nahezu unbegrenzt</haltbarkeit>
    <preis>ab 5 Dukaten, je nach dämonischem Material</preis>
    <rezeptur>
      12 Unzen Wachs aus den Knochen schwarzer Rinder,
      1 Alraune, mindestens 1 Skrupel Material dämonischer
      Herkunft, etwa 3 Unzen Asche aus verbrannter Haut einer
      schwarzen Schlange, ein Büschel eigene Haare
    </rezeptur>
    <wirkung>
      <M>
        1, 3, 4, 12, 13, 14, 16, 17, 22, der Beschwörer ist durch den
        Gestank der entzündeten Kerzen so abgelenkt, dass er einen
        Malus von 3 Punkten auf die Zauberprobe eines Spruchs mit
        dem Merkmal Beschwörung erhält.
      </M>
      <A>Der Rauch wirkt anziehend auf Mindergeister.</A>
      <B>Beschwörungsprobe –1</B>
      <C>Beherrschungsprobe bei Dämonen und Geistern –1</C>
      <D>Beschwörungs- und Beherrschungsprobe jeweils –1</D>
      <E>Beschwörungs- und Beherrschungsprobe jeweils –2</E>
      <F>
        Beschwörungs- und Beherrschungsprobe jeweils –3, jedoch
        steigt auch die Wahrscheinlichkeit, bei einer misslungenen Beschwörung
        versehentlich einen Dämonen aus der nächsthöheren
        Gruppe zu beschwören, auf 50 %.
      </F>
    </wirkung>
    <seite>71</seite>
  </rezept>
  <rezept>
    <name>Zauberkreide</name>
    <gruppe>Magica</gruppe>
    <beschaffung>
      <kosten>25 S</kosten>
      <seltenheit>13</seltenheit>
    </beschaffung>
    <labor>0</labor>
    <probe>
      <brauen>2</brauen>
      <analyse>1</analyse>
    </probe>
    <verbreitung>7</verbreitung>
    <haltbarkeit>nahezu unbegrenzt</haltbarkeit>
    <preis>etwa 5 Dukaten.</preis>
    <rezeptur>
      6 Unzen Olporter Kreidepulver, 1 Alraune, 1 Hahnenkamm,
      2 Unzen getrocknetes Ochsenblut
    </rezeptur>
    <wirkung>
      <M>
        1, 3, 4, 40, bei einem mit misslungener Kreide gezeichneten
        Beschwörungszirkel sind sowohl alle Beschwörungs- als auch
        alle Beherrschungsproben gegenüber der gerufenen Wesenheit
        um 3 Punkte erschwert, selbiges gilt für die Proben bei Austreibungen
        (PENTAGRAMMA, GEISTERBANN ...).
      </M>
      <A>Beschwörungsprobe –1</A>
      <B>Exorzismusprobe –1</B>
      <C>Beschwörungsprobe und Exorzismusprobe je –1</C>
      <D>Beschwörungs-, Beherrschungs- und Exorzismusprobe je –1</D>
      <E>
        Beschwörungsprobe und Exorzismusprobe je –2, Beherrschungsprobe
        –1
      </E>
      <F>
        Beschwörungsprobe und Exorzismusprobe je –3, Beherrschungsprobe
        –2, jedoch steigt auch die Wahrscheinlichkeit, bei
        einer misslungenen Beschwörung versehentlich einen Dämonen
        aus der nächsthöheren Gruppe zu beschwören, auf 50 %.
      </F>
    </wirkung>
    <seite>74</seite>
  </rezept>
</Alchemie>
